#! /bin/sh
path=`pwd`
for file in `ls`;
do
    if [ "$file" != "install" ] && [ "$file" != "uninstall" ] ; then
        echo "install:/usr/share/gnome-shell/extensions/"$file
        sudo ln -s $path/$file /usr/share/gnome-shell/extensions/$file
    fi
done
